### ISSUE TITLE
What is the difference between the results of choosing autocrine and paracrine?

### ISSUE THREAD

**Issue by realzehuali** [SCA-IRCM/SingleCellSignalR#19]
I noticed that the default method is paracrine. But I got more interactions when I chose the autocrine method. The data frame result of autocrine method could also include autocrine|paracrine. So is autocrine better? What is the difference between the results of choosing autocrine and paracrine? Thanks for any help!

**Comment by dactylogram** [comment]
I also faced the same situation like you.
I reviewed the code of 'cell_signaling' in this github, and I found how the definition of autocrine and paracrine differed.

Let's suppose we are finding a ligand-receptor set in cluster A (ligand, ex. EGF) and cluster B (receptor, ex. EGFR),

If cluster A has EGFR gene, this ligand-receptor set is 'Autocrine'.
**... rec.temp <- rec.temp[is.element(rec.temp,rec.tmp)] # line 175**
Otherwise, if cluster A does not have EGFR gene, this ligand-receptor set is 'Paracrine'
**... rec.temp <- rec.temp[!is.element(rec.temp,rec.tmp)] # line 282**

To my best knowledge, paracrine method yields favorable results if clustering method is correct.
But when clustering method is relatively incorrect and some clusters do not consist of cells from biologically identical cell groups, the results of autocrine method may include 'paracrine' ligand-receptor sets.

**Comment by SCA-IRCM** [comment]
Hi,

In the `details` of the **cell_signaling** function you can find a more precise description:

> The “paracrine” option looks for ligands expressed in cluster A and their associated receptors according to LRdb that are expressed in any other cluster but A. These interactions are labelled “paracrine”. The interactions that involve a ligand and a receptor, both differentially expressed in their respective cell clusters according to the edgeR analysis performed by the cluster_analysis() function, are labelled “specific”.
> 
> The “autocrine” option searches for ligands expressed in cell cluster A and their associated receptors also expressed in A. These interactions are labelled “autocrine”. Additionally, it searches for those associated receptors in the other cell clusters (not A) to cover the part of the signaling that is “autocrine” and “paracrine” simultaneously. These interactions are labelled “autocrine/paracrine”.

I agree with dactylogram that _paracrine method yields favorable results if clustering method is correct_.*

Sorry for this late answer and thanks for usinfg **SingleCellSignalR**!

SCA
